name: Build & test on ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: fantomas
        run: |
          dotnet tool install --global fantomas-tool --version 4.4.0-alpha-008

          # path taken from https://stackoverflow.com/a/65367006/544947
          $HOME/.dotnet/tools/fantomas --recurse .
          git diff --exit-code
